### ISSUE TITLE
寻找数组前K个最小数字的问题

### ISSUE THREAD

**Issue by Notzuonotdied** [A11Might/CodingInterview#1]
在`https://github.com/A11Might/CodingInterview/blob/master/code/offer40.java`中。

有个边界问题可能没有考虑到，如果K大于提供的数组的长度的时候没有考虑到。

```java
if (input == null || input.length == 0 || k == 0 || k > input.length) {
    return new ArrayList<>();
}
```

**Comment by A11Might** [comment]
oj 中题目有写 k 一定是合法的。
限制：
0 <= k <= arr.length <= 10000
0 <= arr[i] <= 10000
